language: python

python:
  - "2.7"

services:
  - sqlite3

env:
  - DJANGO_VERSION=1.9.1

install:
  - pip install -r requirements.txt

script:
  - python manage.py check

branches:
  only:
  - master
